/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type MetaTitle = {
  pl?: string
  en?: string
}

export type MetaDescription = {
  pl?: string
  en?: string
}

export type ConferenceRoom = {
  _id: string
  _type: 'conferenceRoom'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: LocaleString
  slug?: Slug
  capacitySeating?: number
  capacityStanding?: number
  description?: LocaleText
  equipment?: Array<
    {
      _key: string
    } & LocaleString
  >
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
}

export type LocaleText = {
  _type: 'localeText'
  pl?: string
  en?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type LocaleString = {
  _type: 'localeString'
  pl?: string
  en?: string
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headerLogo?: ImageWithAlt
  heroImage?: ImageWithAlt
  contactSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    addressLabel?: LocaleString
    phoneLabel?: LocaleString
    emailLabel?: LocaleString
  }
  seo?: SeoMeta
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type SeoMeta = {
  _type: 'seoMeta'
  metaTitle?: MetaTitle
  metaDescription?: MetaDescription
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  noIndex?: boolean
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: LocaleString
}

export type EventTypeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'eventType'
}

export type EventHallReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'eventHall'
}

export type EventsPage = {
  _id: string
  _type: 'eventsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headerLogo?: ImageWithAlt
  hero?: {
    eyebrow?: LocaleString
    title?: LocaleString
    subtitle?: LocaleText
    primaryCtaLabel?: LocaleString
    secondaryCtaLabel?: LocaleString
    image?: ImageWithAlt
  }
  promiseSection?: {
    leadText?: LocaleText
    highlightedText?: LocaleText
    tailText?: LocaleText
    ctaLabel?: LocaleString
  }
  eventTypesSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
  }
  eventTypes?: Array<
    {
      _key: string
    } & EventTypeReference
  >
  hallsSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
  }
  halls?: Array<
    {
      _key: string
    } & EventHallReference
  >
  hotelUpsellSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    ctaLabel?: LocaleString
  }
  cateringSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    image?: ImageWithAlt
  }
  reviewsSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    ratingValue?: string
    ratingSource?: string
    ratingCount?: LocaleString
  }
  stepsSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    steps?: Array<{
      text?: LocaleText
      _type: 'step'
      _key: string
    }>
  }
  reservationSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    formInvitationTitle?: LocaleString
    formInvitationText?: LocaleText
    ctaLabel?: LocaleString
  }
  seo?: SeoMeta
}

export type HotelPage = {
  _id: string
  _type: 'hotelPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headerLogo?: ImageWithAlt
  hero?: {
    eyebrow?: LocaleString
    title?: LocaleString
    subtitle?: LocaleText
    primaryCtaLabel?: LocaleString
    secondaryCtaLabel?: LocaleString
    image?: ImageWithAlt
  }
  quote?: LocaleText
  amenitiesSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    items?: Array<{
      title?: LocaleString
      description?: LocaleText
      icon?: string
      _type: 'amenity'
      _key: string
    }>
  }
  reviewsSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    ratingValue?: string
    ratingSource?: string
    ratingCount?: LocaleString
  }
  discoverSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    cards?: Array<{
      eyebrow?: LocaleString
      title?: LocaleString
      description?: LocaleText
      ctaLabel?: LocaleString
      ctaHref?: string
      image?: ImageWithAlt
      _type: 'discoverCard'
      _key: string
    }>
  }
  reservationSection?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    ctaLabel?: LocaleString
    image?: ImageWithAlt
  }
  seo?: SeoMeta
}

export type BistroPage = {
  _id: string
  _type: 'bistroPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headerLogo?: ImageWithAlt
  heroHeadline?: LocaleString
  menuIntroHeading?: LocaleString
  menuIntroBody?: LocaleText
  centralBanner?: LocaleString
  hoursText?: LocaleText
  seo?: SeoMeta
}

export type MenuPage = {
  _id: string
  _type: 'menuPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  pageIntro?: {
    eyebrow?: LocaleString
    title?: LocaleString
    subtitle?: LocaleText
    ctaLabel?: LocaleString
  }
  photoStrip?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  reservationSection?: {
    title?: LocaleString
    description?: LocaleText
  }
  dietaryInfo?: LocaleText
  seo?: SeoMeta
}

export type RestaurantPage = {
  _id: string
  _type: 'restaurantPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headerLogo?: ImageWithAlt
  heroHeadline?: LocaleString
  heroImage?: ImageWithAlt
  pitchSection?: {
    text?: LocaleText
    ctaLabel?: LocaleString
  }
  craftSection?: {
    title?: LocaleString
    description?: LocaleText
    primaryImage?: ImageWithAlt
    secondaryImage?: ImageWithAlt
    ctaLabel?: LocaleString
  }
  ambianceSection?: {
    title?: LocaleString
    tagline?: LocaleText
    ctaLabel?: LocaleString
    image?: ImageWithAlt
  }
  reservationSection?: {
    title?: LocaleString
    description?: LocaleText
  }
  seo?: SeoMeta
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headerLogo?: ImageWithAlt
  hero?: Hero
  aboutSection?: {
    intro?: LocaleText
    introMobile?: LocaleText
    stats?: Array<{
      value?: string
      label?: LocaleString
      _type: 'stat'
      _key: string
    }>
  }
  servicesIntro?: {
    eyebrow?: LocaleString
    title?: LocaleString
  }
  eventsBlock?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    mainImage?: ImageWithAlt
    secondaryImage?: ImageWithAlt
    ctaLabel?: LocaleString
  }
  restaurantBlock?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    image?: ImageWithAlt
    ctaLabel?: LocaleString
  }
  hotelBlock?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    images?: Array<
      {
        _key: string
      } & ImageWithAlt
    >
    ctaLabel?: LocaleString
  }
  bistroBlock?: {
    eyebrow?: LocaleString
    title?: LocaleString
    description?: LocaleText
    image?: ImageWithAlt
    ctaLabel?: LocaleString
  }
  reviewsBlock?: {
    eyebrow?: LocaleString
    title?: LocaleString
    ratingValue?: string
    ratingSource?: string
    ratingCount?: LocaleString
  }
  contactBlock?: {
    eyebrow?: LocaleString
    title?: LocaleString
    image?: ImageWithAlt
  }
  seo?: SeoMeta
}

export type Hero = {
  _type: 'hero'
  headline?: LocaleString
  headlineMobile?: LocaleString
  subheadline?: LocaleText
  subheadlineMobile?: LocaleText
  image?: ImageWithAlt
  primaryCtaLabel?: LocaleString
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  companyName?: LocaleString
  legalName?: string
  shortDescription?: LocaleText
  address?: Address
  phone?: string
  receptionEmail?: string
  publicEmail?: string
  openingHoursRestaurant?: Array<
    {
      _key: string
    } & OpeningHoursEntry
  >
  openingHoursReception?: Array<
    {
      _key: string
    } & OpeningHoursEntry
  >
  googleBusinessProfileUrl?: string
  googleMapsUrl?: string
  defaultHeaderLogo?: ImageWithAlt
  favicon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  defaultSeo?: SeoMeta
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Address = {
  _type: 'address'
  street?: string
  postalCode?: string
  city?: string
  region?: string
  country?: string
  latitude?: number
  longitude?: number
}

export type RoomType = {
  _id: string
  _type: 'roomType'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: LocaleString
  identifier?: 'apartment-comfort' | 'comfort-room' | 'standard-room'
  description?: LocaleText
  capacity?: number
  amenities?: Array<
    {
      _key: string
    } & LocaleString
  >
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  order?: number
}

export type EventHall = {
  _id: string
  _type: 'eventHall'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: LocaleString
  slug?: Slug
  capacity?: number
  description?: LocaleText
  amenities?: Array<
    {
      _key: string
    } & LocaleString
  >
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  order?: number
  suitableFor?: Array<
    {
      _key: string
    } & EventTypeReference
  >
}

export type MenuCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'menuCategory'
}

export type MenuItem = {
  _id: string
  _type: 'menuItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: LocaleString
  description?: LocaleText
  price?: number
  category?: MenuCategoryReference
  diet?: Array<string>
  image?: ImageWithAlt
  order?: number
  available?: boolean
}

export type MenuCategory = {
  _id: string
  _type: 'menuCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  cuisine?: 'restaurant' | 'bistro'
  name?: LocaleString
  slug?: Slug
  description?: LocaleText
  order?: number
}

export type EventType = {
  _id: string
  _type: 'eventType'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: LocaleString
  slug?: Slug
  description?: LocaleText
  image?: ImageWithAlt
  order?: number
}

export type CtaBlock = {
  _type: 'ctaBlock'
  title?: LocaleString
  description?: LocaleText
  ctaLabel?: LocaleString
}

export type OpeningHoursEntry = {
  _type: 'openingHoursEntry'
  daysOfWeek?: Array<string>
  opens?: string
  closes?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | MetaTitle
  | MetaDescription
  | ConferenceRoom
  | LocaleText
  | Slug
  | LocaleString
  | ContactPage
  | SanityImageAssetReference
  | SeoMeta
  | ImageWithAlt
  | EventTypeReference
  | EventHallReference
  | EventsPage
  | HotelPage
  | BistroPage
  | MenuPage
  | RestaurantPage
  | Homepage
  | Hero
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Address
  | RoomType
  | EventHall
  | MenuCategoryReference
  | MenuItem
  | MenuCategory
  | EventType
  | CtaBlock
  | OpeningHoursEntry
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    companyName,    legalName,    shortDescription,    address,    phone,    receptionEmail,    publicEmail,    openingHoursRestaurant,    openingHoursReception,    googleBusinessProfileUrl,    googleMapsUrl,    defaultHeaderLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    favicon { asset->{ url } },    defaultSeo {        metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  companyName: LocaleString | null
  legalName: string | null
  shortDescription: LocaleText | null
  address: Address | null
  phone: string | null
  receptionEmail: string | null
  publicEmail: string | null
  openingHoursRestaurant: Array<
    {
      _key: string
    } & OpeningHoursEntry
  > | null
  openingHoursReception: Array<
    {
      _key: string
    } & OpeningHoursEntry
  > | null
  googleBusinessProfileUrl: string | null
  googleMapsUrl: string | null
  defaultHeaderLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  favicon: {
    asset: {
      url: string | null
    } | null
  } | null
  defaultSeo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage" && _id == "homepage"][0]{    headerLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    hero {   headline,  headlineMobile,  subheadline,  subheadlineMobile,  primaryCtaLabel,  image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt } },    aboutSection {      intro,      introMobile,      stats[]{ value, label }    },    servicesIntro { eyebrow, title },    eventsBlock {      eyebrow, title, description, ctaLabel,      mainImage {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },      secondaryImage {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    restaurantBlock {      eyebrow, title, description, ctaLabel,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    hotelBlock {      eyebrow, title, description, ctaLabel,      images[]{   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    bistroBlock {      eyebrow, title, description, ctaLabel,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    reviewsBlock {      eyebrow, title, ratingValue, ratingSource, ratingCount    },    contactBlock {      eyebrow, title,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    seo {   metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex }  }
export type HOMEPAGE_QUERY_RESULT = {
  headerLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  hero: {
    headline: LocaleString | null
    headlineMobile: LocaleString | null
    subheadline: LocaleText | null
    subheadlineMobile: LocaleText | null
    primaryCtaLabel: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  aboutSection: {
    intro: LocaleText | null
    introMobile: LocaleText | null
    stats: Array<{
      value: string | null
      label: LocaleString | null
    }> | null
  } | null
  servicesIntro: {
    eyebrow: LocaleString | null
    title: LocaleString | null
  } | null
  eventsBlock: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    ctaLabel: LocaleString | null
    mainImage: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
    secondaryImage: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  restaurantBlock: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    ctaLabel: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  hotelBlock: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    ctaLabel: LocaleString | null
    images: Array<{
      _key: string
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    }> | null
  } | null
  bistroBlock: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    ctaLabel: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  reviewsBlock: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    ratingValue: string | null
    ratingSource: string | null
    ratingCount: LocaleString | null
  } | null
  contactBlock: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  seo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: RESTAURANT_PAGE_QUERY
// Query: *[_type == "restaurantPage" && _id == "restaurantPage"][0]{    headerLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    heroHeadline,    heroImage {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    pitchSection { text, ctaLabel },    craftSection {      title, description, ctaLabel,      primaryImage {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },      secondaryImage {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    ambianceSection {      title, tagline, ctaLabel,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    reservationSection { title, description },    seo {   metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex }  }
export type RESTAURANT_PAGE_QUERY_RESULT = {
  headerLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  heroHeadline: LocaleString | null
  heroImage: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  pitchSection: {
    text: LocaleText | null
    ctaLabel: LocaleString | null
  } | null
  craftSection: {
    title: LocaleString | null
    description: LocaleText | null
    ctaLabel: LocaleString | null
    primaryImage: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
    secondaryImage: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  ambianceSection: {
    title: LocaleString | null
    tagline: LocaleText | null
    ctaLabel: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  reservationSection: {
    title: LocaleString | null
    description: LocaleText | null
  } | null
  seo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: MENU_PAGE_QUERY
// Query: *[_type == "menuPage" && _id == "menuPage"][0]{    "restaurantHeaderLogo": *[_type == "restaurantPage" && _id == "restaurantPage"][0].headerLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    pageIntro { eyebrow, title, subtitle, ctaLabel },    photoStrip[]{   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    reservationSection { title, description },    dietaryInfo,    seo {   metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex }  }
export type MENU_PAGE_QUERY_RESULT = {
  restaurantHeaderLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  pageIntro: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    subtitle: LocaleText | null
    ctaLabel: LocaleString | null
  } | null
  photoStrip: Array<{
    _key: string
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  }> | null
  reservationSection: {
    title: LocaleString | null
    description: LocaleText | null
  } | null
  dietaryInfo: LocaleText | null
  seo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: BISTRO_PAGE_QUERY
// Query: *[_type == "bistroPage" && _id == "bistroPage"][0]{    headerLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    heroHeadline,    menuIntroHeading,    menuIntroBody,    centralBanner,    hoursText,    seo {   metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex }  }
export type BISTRO_PAGE_QUERY_RESULT = {
  headerLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  heroHeadline: LocaleString | null
  menuIntroHeading: LocaleString | null
  menuIntroBody: LocaleText | null
  centralBanner: LocaleString | null
  hoursText: LocaleText | null
  seo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: BISTRO_MENU_QUERY
// Query: *[_type == "menuCategory" && cuisine == "bistro"]    | order(order asc) {      _id,      name,      "slug": slug.current,      description,      order,      "items": *[_type == "menuItem" && references(^._id) && available == true] | order(order asc) {        _id,        name,        description,        price,        diet,        image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }      }    }
export type BISTRO_MENU_QUERY_RESULT = Array<{
  _id: string
  name: LocaleString | null
  slug: string | null
  description: LocaleText | null
  order: number | null
  items: Array<{
    _id: string
    name: LocaleString | null
    description: LocaleText | null
    price: number | null
    diet: Array<string> | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  }>
}>

// Source: lib/sanity/queries.ts
// Variable: HOTEL_PAGE_QUERY
// Query: *[_type == "hotelPage" && _id == "hotelPage"][0]{    headerLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    hero {      eyebrow, title, subtitle, primaryCtaLabel, secondaryCtaLabel,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    quote,    amenitiesSection {      eyebrow, title,      items[]{ title, description, icon }    },    reviewsSection { eyebrow, title, ratingValue, ratingSource, ratingCount },    discoverSection {      eyebrow, title,      cards[]{        eyebrow, title, description, ctaLabel, ctaHref,        image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }      }    },    reservationSection {      eyebrow, title, description, ctaLabel,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    seo {   metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex }  }
export type HOTEL_PAGE_QUERY_RESULT = {
  headerLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  hero: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    subtitle: LocaleText | null
    primaryCtaLabel: LocaleString | null
    secondaryCtaLabel: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  quote: LocaleText | null
  amenitiesSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    items: Array<{
      title: LocaleString | null
      description: LocaleText | null
      icon: string | null
    }> | null
  } | null
  reviewsSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    ratingValue: string | null
    ratingSource: string | null
    ratingCount: LocaleString | null
  } | null
  discoverSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    cards: Array<{
      eyebrow: LocaleString | null
      title: LocaleString | null
      description: LocaleText | null
      ctaLabel: LocaleString | null
      ctaHref: string | null
      image: {
        _type: 'imageWithAlt'
        asset: {
          _id: string
          url: string | null
          metadata: {
            dimensions: SanityImageDimensions | null
            lqip: string | null
            palette: SanityImagePalette | null
          } | null
        } | null
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: LocaleString | null
      } | null
    }> | null
  } | null
  reservationSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    ctaLabel: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  seo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: EVENTS_PAGE_QUERY
// Query: *[_type == "eventsPage" && _id == "eventsPage"][0]{    headerLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    hero {      eyebrow, title, subtitle, primaryCtaLabel, secondaryCtaLabel,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    promiseSection { leadText, highlightedText, tailText, ctaLabel },    eventTypesSection { eyebrow, title, description },    eventTypes[]->{      _id,      name,      "slug": slug.current,      description,      order,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    } | order(order asc),    hallsSection { eyebrow, title, description },    halls[]->{      _id,      name,      "slug": slug.current,      capacity,      description,      amenities,      order,      images[]{   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    } | order(order asc),    hotelUpsellSection { eyebrow, title, description, ctaLabel },    cateringSection {      eyebrow, title, description,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    },    reviewsSection { eyebrow, title, ratingValue, ratingSource, ratingCount },    stepsSection {      eyebrow, title,      steps[]{ text }    },    reservationSection {      eyebrow, title, description,      formInvitationTitle, formInvitationText, ctaLabel    },    seo {   metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex }  }
export type EVENTS_PAGE_QUERY_RESULT = {
  headerLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  hero: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    subtitle: LocaleText | null
    primaryCtaLabel: LocaleString | null
    secondaryCtaLabel: LocaleString | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  promiseSection: {
    leadText: LocaleText | null
    highlightedText: LocaleText | null
    tailText: LocaleText | null
    ctaLabel: LocaleString | null
  } | null
  eventTypesSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
  } | null
  eventTypes: Array<{
    _id: string
    name: LocaleString | null
    slug: string | null
    description: LocaleText | null
    order: number | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  }> | null
  hallsSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
  } | null
  halls: Array<{
    _id: string
    name: LocaleString | null
    slug: string | null
    capacity: number | null
    description: LocaleText | null
    amenities: Array<
      {
        _key: string
      } & LocaleString
    > | null
    order: number | null
    images: Array<{
      _key: string
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    }> | null
  }> | null
  hotelUpsellSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    ctaLabel: LocaleString | null
  } | null
  cateringSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  } | null
  reviewsSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    ratingValue: string | null
    ratingSource: string | null
    ratingCount: LocaleString | null
  } | null
  stepsSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    steps: Array<{
      text: LocaleText | null
    }> | null
  } | null
  reservationSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    description: LocaleText | null
    formInvitationTitle: LocaleString | null
    formInvitationText: LocaleText | null
    ctaLabel: LocaleString | null
  } | null
  seo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{    headerLogo {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    heroImage {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt },    contactSection {      eyebrow, title,      addressLabel, phoneLabel, emailLabel    },    seo {   metaTitle,  metaDescription,  ogImage { ..., asset->{ _id, url } },  noIndex }  }
export type CONTACT_PAGE_QUERY_RESULT = {
  headerLogo: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  heroImage: {
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  } | null
  contactSection: {
    eyebrow: LocaleString | null
    title: LocaleString | null
    addressLabel: LocaleString | null
    phoneLabel: LocaleString | null
    emailLabel: LocaleString | null
  } | null
  seo: {
    metaTitle: MetaTitle | null
    metaDescription: MetaDescription | null
    ogImage: {
      asset: {
        _id: string
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: lib/sanity/queries.ts
// Variable: MENU_BY_CATEGORY_QUERY
// Query: *[_type == "menuCategory" && cuisine == "restaurant"] | order(order asc) {    _id,    name,    "slug": slug.current,    description,    order,    "items": *[_type == "menuItem" && references(^._id) && available == true] | order(order asc) {      _id,      name,      description,      price,      diet,      image {   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }    }  }
export type MENU_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string
  name: LocaleString | null
  slug: string | null
  description: LocaleText | null
  order: number | null
  items: Array<{
    _id: string
    name: LocaleString | null
    description: LocaleText | null
    price: number | null
    diet: Array<string> | null
    image: {
      _type: 'imageWithAlt'
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
          palette: SanityImagePalette | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: LocaleString | null
    } | null
  }>
}>

// Source: lib/sanity/queries.ts
// Variable: ALL_EVENT_HALLS_QUERY
// Query: *[_type == "eventHall"] | order(order asc) {    _id,    name,    "slug": slug.current,    capacity,    description,    amenities,    order,    images[]{   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }  }
export type ALL_EVENT_HALLS_QUERY_RESULT = Array<{
  _id: string
  name: LocaleString | null
  slug: string | null
  capacity: number | null
  description: LocaleText | null
  amenities: Array<
    {
      _key: string
    } & LocaleString
  > | null
  order: number | null
  images: Array<{
    _key: string
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  }> | null
}>

// Source: lib/sanity/queries.ts
// Variable: ALL_ROOM_TYPES_QUERY
// Query: *[_type == "roomType"] | order(order asc) {    _id,    name,    identifier,    capacity,    description,    amenities,    order,    images[]{   ...,  asset->{    _id,    url,    metadata { dimensions, lqip, palette }  },  alt }  }
export type ALL_ROOM_TYPES_QUERY_RESULT = Array<{
  _id: string
  name: LocaleString | null
  identifier: 'apartment-comfort' | 'comfort-room' | 'standard-room' | null
  capacity: number | null
  description: LocaleText | null
  amenities: Array<
    {
      _key: string
    } & LocaleString
  > | null
  order: number | null
  images: Array<{
    _key: string
    _type: 'imageWithAlt'
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
        palette: SanityImagePalette | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: LocaleString | null
  }> | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    companyName,\n    legalName,\n    shortDescription,\n    address,\n    phone,\n    receptionEmail,\n    publicEmail,\n    openingHoursRestaurant,\n    openingHoursReception,\n    googleBusinessProfileUrl,\n    googleMapsUrl,\n    defaultHeaderLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    favicon { asset->{ url } },\n    defaultSeo {\n      \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT
    '\n  *[_type == "homepage" && _id == "homepage"][0]{\n    headerLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    hero { \n  headline,\n  headlineMobile,\n  subheadline,\n  subheadlineMobile,\n  primaryCtaLabel,\n  image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n },\n    aboutSection {\n      intro,\n      introMobile,\n      stats[]{ value, label }\n    },\n    servicesIntro { eyebrow, title },\n    eventsBlock {\n      eyebrow, title, description, ctaLabel,\n      mainImage { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n      secondaryImage { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    restaurantBlock {\n      eyebrow, title, description, ctaLabel,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    hotelBlock {\n      eyebrow, title, description, ctaLabel,\n      images[]{ \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    bistroBlock {\n      eyebrow, title, description, ctaLabel,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    reviewsBlock {\n      eyebrow, title, ratingValue, ratingSource, ratingCount\n    },\n    contactBlock {\n      eyebrow, title,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    seo { \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n }\n  }\n': HOMEPAGE_QUERY_RESULT
    '\n  *[_type == "restaurantPage" && _id == "restaurantPage"][0]{\n    headerLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    heroHeadline,\n    heroImage { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    pitchSection { text, ctaLabel },\n    craftSection {\n      title, description, ctaLabel,\n      primaryImage { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n      secondaryImage { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    ambianceSection {\n      title, tagline, ctaLabel,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    reservationSection { title, description },\n    seo { \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n }\n  }\n': RESTAURANT_PAGE_QUERY_RESULT
    '\n  *[_type == "menuPage" && _id == "menuPage"][0]{\n    "restaurantHeaderLogo": *[_type == "restaurantPage" && _id == "restaurantPage"][0].headerLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    pageIntro { eyebrow, title, subtitle, ctaLabel },\n    photoStrip[]{ \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    reservationSection { title, description },\n    dietaryInfo,\n    seo { \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n }\n  }\n': MENU_PAGE_QUERY_RESULT
    '\n  *[_type == "bistroPage" && _id == "bistroPage"][0]{\n    headerLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    heroHeadline,\n    menuIntroHeading,\n    menuIntroBody,\n    centralBanner,\n    hoursText,\n    seo { \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n }\n  }\n': BISTRO_PAGE_QUERY_RESULT
    '\n  *[_type == "menuCategory" && cuisine == "bistro"]\n    | order(order asc) {\n      _id,\n      name,\n      "slug": slug.current,\n      description,\n      order,\n      "items": *[_type == "menuItem" && references(^._id) && available == true] | order(order asc) {\n        _id,\n        name,\n        description,\n        price,\n        diet,\n        image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n      }\n    }\n': BISTRO_MENU_QUERY_RESULT
    '\n  *[_type == "hotelPage" && _id == "hotelPage"][0]{\n    headerLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    hero {\n      eyebrow, title, subtitle, primaryCtaLabel, secondaryCtaLabel,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    quote,\n    amenitiesSection {\n      eyebrow, title,\n      items[]{ title, description, icon }\n    },\n    reviewsSection { eyebrow, title, ratingValue, ratingSource, ratingCount },\n    discoverSection {\n      eyebrow, title,\n      cards[]{\n        eyebrow, title, description, ctaLabel, ctaHref,\n        image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n      }\n    },\n    reservationSection {\n      eyebrow, title, description, ctaLabel,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    seo { \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n }\n  }\n': HOTEL_PAGE_QUERY_RESULT
    '\n  *[_type == "eventsPage" && _id == "eventsPage"][0]{\n    headerLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    hero {\n      eyebrow, title, subtitle, primaryCtaLabel, secondaryCtaLabel,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    promiseSection { leadText, highlightedText, tailText, ctaLabel },\n    eventTypesSection { eyebrow, title, description },\n    eventTypes[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      description,\n      order,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    } | order(order asc),\n    hallsSection { eyebrow, title, description },\n    halls[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      capacity,\n      description,\n      amenities,\n      order,\n      images[]{ \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    } | order(order asc),\n    hotelUpsellSection { eyebrow, title, description, ctaLabel },\n    cateringSection {\n      eyebrow, title, description,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    },\n    reviewsSection { eyebrow, title, ratingValue, ratingSource, ratingCount },\n    stepsSection {\n      eyebrow, title,\n      steps[]{ text }\n    },\n    reservationSection {\n      eyebrow, title, description,\n      formInvitationTitle, formInvitationText, ctaLabel\n    },\n    seo { \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n }\n  }\n': EVENTS_PAGE_QUERY_RESULT
    '\n  *[_type == "contactPage" && _id == "contactPage"][0]{\n    headerLogo { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    heroImage { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n },\n    contactSection {\n      eyebrow, title,\n      addressLabel, phoneLabel, emailLabel\n    },\n    seo { \n  metaTitle,\n  metaDescription,\n  ogImage { ..., asset->{ _id, url } },\n  noIndex\n }\n  }\n': CONTACT_PAGE_QUERY_RESULT
    '\n  *[_type == "menuCategory" && cuisine == "restaurant"] | order(order asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    order,\n    "items": *[_type == "menuItem" && references(^._id) && available == true] | order(order asc) {\n      _id,\n      name,\n      description,\n      price,\n      diet,\n      image { \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n    }\n  }\n': MENU_BY_CATEGORY_QUERY_RESULT
    '\n  *[_type == "eventHall"] | order(order asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    capacity,\n    description,\n    amenities,\n    order,\n    images[]{ \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n  }\n': ALL_EVENT_HALLS_QUERY_RESULT
    '\n  *[_type == "roomType"] | order(order asc) {\n    _id,\n    name,\n    identifier,\n    capacity,\n    description,\n    amenities,\n    order,\n    images[]{ \n  ...,\n  asset->{\n    _id,\n    url,\n    metadata { dimensions, lqip, palette }\n  },\n  alt\n }\n  }\n': ALL_ROOM_TYPES_QUERY_RESULT
  }
}
